name: gitradar_server
description: GitRadar server built with Serverpod.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: ^3.0.0
  # Encryption for PAT storage
  encrypt: ^5.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  serverpod_test: ^3.0.0
